### ISSUE TITLE
Break old test after add gem

### ISSUE THREAD

**Issue by ovictorpinto** [harrylewis/rspec-snapshot#21]
Hi,
I have a big project, and after added rspec-snapshot a lot of tests break. Should the tests run outsite the test context? Seems like mocks are interfering in snapshot process, even if the test don't use snapshot.

```
describe "TestClass" do

  context "problems" do
    describe "mocking ENV" do
      before do
        allow(ENV).to receive(:[]).with("PARAMETER") { "false" }
      end
      it "it" do
        expect(1).to be 1
      end
    end
    describe "mocking File" do
      before do
        expect(File).to receive(:read).and_return({})
      end
      it "it" do
        File.read("file.rb")
        expect(1).to be 1
      end
    end
  end
```
result:
```
RSpec::Mocks::MockExpectationError:  received :[] with unexpected arguments
  expected: ("PARAMETER")
       got: ("UPDATE_SNAPSHOTS")
 Please stub a default value first if message might be received with other args as well. 


  0) TestClass problems mocking ENV it
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

      received :[] with unexpected arguments
         expected: ("PARAMETER")
              got: ("UPDATE_SNAPSHOTS")
        Please stub a default value first if message might be received with other args as well. 
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing.rb:7:in `update?'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/recorder.rb:5:in `initialize'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/rspec.rb:10:in `new'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/rspec.rb:10:in `block in included'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/rspec.rb:17:in `block in included'

TypeError: no implicit conversion of Hash into String

  0) TestClass problems mocking File it
     Failure/Error: eval(input)

     TypeError:
       no implicit conversion of Hash into String
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/snapshot.rb:20:in `eval'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/snapshot.rb:20:in `load'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/snapshot.rb:15:in `load_file'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/recorder.rb:21:in `snapshots'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/recorder.rb:122:in `obsolete'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/recorder.rb:70:in `commit'
     # /Users/victorpinto/.rvm/gems/ruby-2.7.1/gems/snapshot_testing-0.3.4/lib/snapshot_testing/rspec.rb:17:in `block in included'

```

When I remove the gem:
```
2 examples, 0 failures, 2 passed

Finished in 0.257794 seconds


Randomized with seed 43369

Process finished with exit code 0
```
